services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,0.0.0.0
      DJANGO_SECRET_KEY: django_secret
      DJANGO_SETTINGS_MODULE: zackads.settings.prod
      SECURE_SSL_REDIRECT: "0"
      DEBUG: "1"
    depends_on:
      - db

volumes:
  postgres_data:
