# Generated by Django 5.2 on 2025-05-15 08:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFileProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('comp_arch', 'computer architecture'), ('data', 'data-driven computer science'), ('prob_ii', 'probability 2')], max_length=9)),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('static_problem_path', models.CharField(max_length=255)),
                ('static_solution_path', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'question_number'), name='unique_problem')],
            },
        ),
        migrations.CreateModel(
            name='StaticFileProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.IntegerField(choices=[(0, 'Not Attempted'), (1, 'Hard'), (2, 'Medium'), (3, 'Easy')])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_questions.staticfileproblem')),
            ],
        ),
    ]
