# Generated by Django 5.1.7 on 2025-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("comp_arch", "Computer Architecture"),
                            ("prob_ii", "Probability II"),
                            ("data", "Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("problem_id", models.CharField(max_length=20)),
            ],
        ),
    ]
