# Generated by Django 5.1.7 on 2025-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemattempt",
            name="confidence",
            field=models.IntegerField(
                choices=[(0, "not_attempted"), (1, "hard"), (2, "medium"), (3, "easy")]
            ),
        ),
        migrations.AlterField(
            model_name="problemattempt",
            name="subject",
            field=models.CharField(
                choices=[
                    ("comp_arch", "comp_arch"),
                    ("prob_ii", "prob_ii"),
                    ("data", "data"),
                ],
                max_length=20,
            ),
        ),
    ]
