# Generated by Django 5.1.7 on 2025-04-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemattempt",
            old_name="problem_id",
            new_name="question",
        ),
        migrations.AddField(
            model_name="problemattempt",
            name="confidence",
            field=models.IntegerField(
                choices=[(0, "Hard"), (1, "Medium"), (2, "Easy")], default=0
            ),
            preserve_default=False,
        ),
    ]
