# Generated by Django 5.1.7 on 2025-04-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper_questions", "0002_alter_problemattempt_confidence_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProblemAttempt",
            new_name="StaticFileProblemAttempt",
        ),
    ]
