# Generated by Django 5.2 on 2025-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('question_file', models.FileField(upload_to='pgrind/problems/questions/')),
                ('solution_file', models.FileField(upload_to='pgrind/problems/solutions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
