# Generated by Django 5.2 on 2025-09-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrind', '0002_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.IntegerField(choices=[(0, 'Not Attempted'), (1, 'Hard'), (2, 'Medium'), (3, 'Easy')])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgrind.problem')),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgrind.subject'),
        ),
    ]
