# Generated by Django 5.2 on 2025-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrind', '0003_subject_attempt_alter_problem_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='question_file',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution_file',
        ),
        migrations.AddField(
            model_name='problem',
            name='question_image',
            field=models.ImageField(default='foo', upload_to='pgrind/problems/questions/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_image',
            field=models.ImageField(default='bar', upload_to='pgrind/problems/solutions/'),
            preserve_default=False,
        ),
    ]
