# Generated by Django 5.2 on 2025-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrind', '0004_remove_problem_question_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='comp_arch', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
